# Generated by Django 3.0.3 on 2020-05-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='account',
            new_name='bank_account',
        ),
    ]
