# Generated by Django 3.0.3 on 2020-05-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_time', models.DateTimeField(blank=True, null=True)),
                ('team_name_1', models.CharField(max_length=100)),
                ('team_name_2', models.CharField(max_length=100)),
                ('team_name_3', models.CharField(max_length=100)),
                ('team_name_4', models.CharField(max_length=100)),
                ('team_odds_1', models.CharField(max_length=20)),
                ('team_odds_2', models.CharField(max_length=20)),
                ('team_odds_3', models.CharField(max_length=20)),
                ('team_odds_4', models.CharField(max_length=20)),
                ('betting_total', models.CharField(max_length=20, null=True)),
                ('betting_now', models.CharField(max_length=20, null=True)),
                ('match_status', models.CharField(blank=True, choices=[('1', '관리자 준비'), ('2', '베팅 진행'), ('3', '베팅 종료'), ('4', '경기 시작'), ('5', '경기 종료')], default='1', help_text='Match availability', max_length=1)),
            ],
            options={
                'ordering': ['match_time', 'match_status'],
            },
        ),
    ]
