# Generated by Django 3.0.3 on 2020-05-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_desc_1',
            field=models.CharField(default='없음', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='match_desc_2',
            field=models.CharField(default='없음', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='betting_now',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='betting_total',
            field=models.CharField(default='10', max_length=20),
        ),
    ]
