# Generated by Django 3.0.3 on 2020-05-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_auto_20200501_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=20)),
                ('account', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.CharField(blank=True, choices=[('1', '관리자 준비'), ('2', '베팅 진행'), ('3', '베팅 종료'), ('4', '경기 시작'), ('5', '경기 종료')], default='1', help_text='해당 결기에 대한 관리 상태', max_length=1),
        ),
    ]
