# Generated by Django 3.0.3 on 2020-05-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_auto_20200501_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=20)),
                ('account', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='account',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='email',
        ),
    ]
