# Generated by Django 3.0.3 on 2020-05-01 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_auto_20200501_1813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Owner',
        ),
    ]
