# Generated by Django 3.0.3 on 2020-05-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0005_auto_20200501_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='code',
            field=models.CharField(default='1004', max_length=10),
        ),
    ]
