# Generated by Django 3.0.3 on 2020-05-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0006_owner_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.CharField(blank=True, choices=[('1', '관리자 준비'), ('2', '베팅 진행'), ('3', '베팅 종료'), ('4', '경기 시작'), ('5', '경기 종료 - 성공'), ('6', '경기 종료 - 실패')], default='1', help_text='해당 결기에 대한 관리 상태', max_length=1),
        ),
    ]
