# Generated by Django 3.0.3 on 2020-05-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0007_auto_20200501_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_condition_1',
            field=models.CharField(blank=True, choices=[('1', '경기 종료 전'), ('2', '적중'), ('3', '미적중'), ('4', '적특')], default='1', help_text='1경기 첫번째 팀 기준 결과', max_length=1),
        ),
        migrations.AddField(
            model_name='match',
            name='match_condition_2',
            field=models.CharField(blank=True, choices=[('1', '경기 종료 전'), ('2', '적중'), ('3', '미적중'), ('4', '적특')], default='1', help_text='2경기 첫번째 팀 결과', max_length=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_desc_1',
            field=models.CharField(default='0점', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_desc_2',
            field=models.CharField(default='0점', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.CharField(blank=True, choices=[('1', '관리자 준비'), ('2', '베팅 진행'), ('3', '베팅 종료'), ('4', '경기 시작'), ('5', '경기 종료')], default='1', help_text='해당 결기에 대한 관리 상태', max_length=1),
        ),
    ]
