# Generated by Django 3.0.3 on 2020-05-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0008_auto_20200502_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_result_1',
            field=models.CharField(blank=True, choices=[('1', '경기 종료 전'), ('2', '적중'), ('3', '미적중'), ('4', '적특')], default='1', help_text='1경기 첫번째 팀 기준 결과', max_length=1),
        ),
        migrations.AddField(
            model_name='match',
            name='match_result_2',
            field=models.CharField(blank=True, choices=[('1', '경기 종료 전'), ('2', '적중'), ('3', '미적중'), ('4', '적특')], default='1', help_text='2경기 첫번째 팀 결과', max_length=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_condition_1',
            field=models.CharField(blank=True, choices=[('U', '언더'), ('O', '오바')], default='U', help_text='1경기 첫번째 팀 기준 언더-오바', max_length=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_condition_2',
            field=models.CharField(blank=True, choices=[('U', '언더'), ('O', '오바')], default='U', help_text='2경기 첫번째 팀 기준 언더-오바', max_length=1),
        ),
    ]
