# Generated by Django 3.0.3 on 2020-05-03 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0009_auto_20200502_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='account',
            new_name='bank_account',
        ),
    ]
